/**
 * bd-o15qnr — every word the coach app v2 shows, in one place, so Urdu can
 * follow (language-protocol: NIETE is flat en/ur; read it before adding a
 * language). Names, schools and numbers are data and come from the API as they
 * are. Words stay short: icons plus 1–3 words, no sentences (v18 design).
 */

export const COACH_COPY = {
  greeting: (name?: string | null) => (name ? `Salaam, ${name}` : "Salaam"),
  coachChip: "Coach",
  home: "Home",
  back: "Back",
  loadFailed: "Could not load",
  retry: "Try again",
  dash: "—",

  // Home
  todaysVisits: "Today's visits",
  next: "Next",
  done: "Done",
  inHours: (h: number) => (h <= 0 ? "Now" : `In ${h} h`),
  takeObservation: "Take observation",

  // Features
  scheduling: "Schedule",
  observe: "Observe",
  schoolsAndTeachers: "Schools & teachers",
  training: "Training",
  thisWeekN: (n: number) => `${n} this week`,
  waitingN: (n: number) => `${n} waiting`,
  inProgressN: (n: number) => `${n} in progress`,
  teachersN: (n: number) => `${n} teachers`,

  // Scheduling
  newVisit: "New visit",
  mySchedule: "My schedule",
  teamSchedule: "Team schedule",
  newVisitChip: "School · teacher · time",
  overdueN: (n: number) => `${n} overdue`,
  coachesN: (n: number) => `${n} coaches`,
  overdue: "Overdue",
  today: "Today",
  daysLate: (n: number) => `${n} days late`,
  earlier: "Earlier",
  earlierDays: "Earlier days",
  laterDays: "Later days",

  // Team
  totals: { today: "Today", week: "This week", month: "This month" },
  coach: "Coach",
  allCoaches: "All coaches",
  you: "You",
  visitsN: (n: number) => `${n} visits`,
  showAllN: (n: number) => `Show all ${n}`,
  showFewer: "Show fewer",
  noVisits: "No visits",

  // New visit
  stepOf: (n: number) => `Step ${n} of 3`,
  pickSchool: "Pick a school",
  pickTeacher: "Pick a teacher",
  pickDayTime: "Pick day and time",
  sortedBySince: "Days since last visit",
  change: "Change",
  profile: "Profile",
  day: "Day",
  time: "Time",
  hour: "Hour",
  minutes: "Minutes",
  amPm: "AM / PM",
  laterHour: "Later hour",
  earlierHour: "Earlier hour",
  booked: "Booked",
  schedule: "Schedule",
  saving: "Saving",
  visitScheduled: "Visit scheduled",
  teachersCount: (n: number) => `${n} teachers`,
  lastVisitDays: (d: number | null) => (d == null ? "No visits yet" : `Last visit ${d} days`),
  reschedule: "Reschedule",

  // Observe
  takeObservationTile: "Take observation",
  reports: "Reports",
  pickTheTeacher: "Pick the teacher",
  scheduleFirst: "Schedule a visit first",
  recordLive: "Record live",
  // bd-o15qnr.9 (v21): "Upload recording" everywhere, the sheet title too.
  attachRecording: "Upload recording",
  observation: "Observation",
  // bd-o15qnr.18 — operator: "Where it says AVG score, it should instead say Avg. HITL Score."
  avgScore: "Avg. HITL Score",
  teacher: "Teacher",
  lastVisitOn: (date: string) => `Last visit · ${date}`,
  hitlBy: (who: string) => `HITL · ${who}`,
  // bd-o15qnr.19 — operator: "Draft should be Feedback Form, Talk should be Debrief."
  reportStep: { sent: "Report sent", report: "Report not sent yet", draft: "Feedback Form", talk: "Debrief", analysing: "Analysing" } as Record<string, string>,

  // Record live (v18 Recording)
  recording: "Recording",
  paused: "Paused",
  recordingTime: "Recording time",
  visitAt: (time: string) => `Visit · ${time}`,
  linked: "Linked",
  pause: "Pause",
  resume: "Resume",
  stop: "Stop",
  stopAsk: "Stop recording?",
  recordedFor: (minutes: string) => `You recorded ${minutes}.`,
  yesStop: "Yes, stop",
  keepRecording: "Keep recording",
  shortNote: "That is short. The report works best on a whole lesson.",
  screenOff: "The screen went off for a while. Part of it may be silent. Keep this screen open.",
  micBlocked: "We can't use the microphone",
  micAllow: "When the phone asks, tap Allow.",
  tryAgain: "Try again",

  // Upload recording (v18 Attach)
  close: "Close",
  chooseFile: "Choose file",
  notAudio: "That is not a recording. Choose a sound file from your phone.",
  tooLarge: "That recording is too large to send.",

  // Check and send (v18 CheckSend)
  checkAndSend: "Check and send",
  lessonOf: (name: string) => `${name}’s lesson`,
  justNow: "just now",
  play: "Play",
  stopPlaying: "Stop playing",
  redo: "Redo",
  shortWarning: "This is under 10 minutes. You can still send it, but the report may be thin.",
  lessonPlan: "Lesson plan",
  optional: "Optional",
  theirRecentPlans: "Their recent plans",
  library: "Library",
  photoOfPlan: "Photo of plan",
  takenNow: "Taken just now",
  noRecentPlans: "No recent plans",
  removePlan: "Remove the lesson plan",
  planNotOk: "That is not a lesson plan photo. Choose a JPG or PNG.",
  boardPhotos: "Board photos",
  upToN: (n: number) => `Up to ${n}`,
  noFaces: "No faces",
  addPhoto: "Add photo",
  removePhoto: (name: string) => `Remove ${name}`,
  tooManyPhotos: (n: number) => `You can add up to ${n} photos.`,
  notAPhoto: "That is not a photo. Choose a JPG or PNG.",
  send: "Send",
  sending: (name: string) => `Sending ${name}’s lesson…`,
  keepOpenSending: "Keep this screen open until it is done.",
  netTitle: "The internet stopped",
  netSafe: "Don't worry. The lesson is safe on this phone.",
  planProblem: "That lesson plan could not be used. Pick another, or take a photo of the plan.",
  notYourTeacher: "That teacher is not in your schools any more.",
  refused: "Something was not accepted. Please try again.",
  noRecording: "No recording yet",
  teacherProfile: "Teacher profile",
  lastVisit: "Last visit",
  cancel: "Cancel",
  cancelVisit: "Cancel visit",
  keepVisit: "Keep visit",
  hitlYou: "HITL",

  // Reports
  waitingForYou: "Waiting for you",
  inProgress: "In progress",
  allObservations: "All observations",
  stepLabel: { draft: "Feedback Form", talk: "Debrief", analysing: "Analysing", report: "Send report", sent: "Sent" } as Record<string, string>,
  steps: ["Analysed", "Feedback Form", "Debrief", "Sent"],

  // The observation page (v24 ObsTrack, bd-o15qnr.19)
  trackSteps: (first: string) => ["Lesson analysed", "Feedback Form", "Debrief", "Your feedback", `Send ${first} the report`],
  yourTurn: "Your turn",
  reportsWaiting: (n: number) => (n === 1 ? "1 report waiting" : `${n} reports waiting`),
  allReports: "All reports",
  onWhatsApp: "On WhatsApp",
  working: "Working",
  dcScore: "Digital Coach score",
  dcScoreOf: (n: string) => `Digital Coach score ${n}`,
  draftBeforeCheck: "Draft · before your check",
  finalScore: "Final score",
  playLesson: "Play lesson",
  pauseLesson: "Pause lesson",
  steps5: "Steps",
  reportOf: (name: string) => `${name}’s report`,
  continueOnWhatsApp: "This observation continues on WhatsApp.",
  stopped: "This observation was stopped.",
  showMore: "Show more",

  // Schools & teachers
  teachersTab: "Teachers",
  schoolsTab: "Schools",
  sort: "Sort",
  sortDays: "Days since visit",
  sortAvg: "Avg. HITL Score",
  sortAz: "A–Z",
  sortLeast: "Least visited",
  sortMost: "Most visited",
  allSchools: "All schools",
  school: "School",
  visitsLast3: "Visits · last 3 months",
  sinceVisit: "Since visit",
  hitl: "HITL",
  dc: "DC",
  avg: "Avg. HITL Score",
  avgHitl: "Avg. HITL Score",
  trainingCol: "Training",
  visitsCol: "Visits",
  teachersCol: "Teachers",
  scheduleVisitHere: "Schedule visit here",
  scheduleVisit: "Schedule visit",
  hitlVisits: "HITL visits",
  dcSessions: "DC sessions",
  modulesDone: "Modules done",
  lastTraining: "Last training",
  examsGenerated: "Exams generated",
  lpOpened: "Lesson plans opened",
  history: "History",
  monthOf: (iso: string) => new Date(iso).toLocaleDateString("en-GB", { month: "long", year: "numeric" }),
  // bd-o15qnr.10 — one HITL report, opened from a teacher's History (`observation` is defined above)
  observedBy: "Observed by",
  reportSent: "Sent",
  summary: "Summary",
  // bd-o15qnr.11 — Edit teacher (school and remove only: /observe has no writer for name, role or level)
  edit: "Edit",
  editTeacher: "Edit teacher",
  nameLabel: "Name",
  phoneLabel: "Phone",
  roleLabel: "Role",
  roleTeacher: "Teacher",
  rolePrincipal: "Principal",
  schoolLabel: "School",
  save: "Save",
  removeFromSchool: "Remove from school",
  remove: "Remove",
  keep: "Keep",
  notYourSchool: "Not your school",
  // bd-o15qnr.13 — name / level / role / phone, through main's /observe edit path
  teachingLevel: "Teaching level",
  levelNames: { PRIMARY: "Primary", MIDDLE: "Middle", HIGH: "High" } as Record<string, string>,
  canObserve: "Can observe teachers",
  checkNumber: "Check number",
  changeNumber: "Change number",
  phoneFree: "Number is free",
  phoneShell: "Old account folded in",
  phoneSame: "Same number",
  phoneInvalid: "Not a valid number",
  editNotYours: "Not your teacher",
  nameNeeded: "Name needed",
  pickLevel: "Pick a level",
  levelLocked: (h: number | null | undefined) => (h ? `Level locked · ${h} h` : "Level locked"),
  saveFailed: "Could not save",
  nextVisitOn: (when: string) => `Next visit: ${when}`,
  searchPlaceholder: "Name or phone",
  schoolSearchPlaceholder: "School name",
  daysShort: (d: number | null) => (d == null ? "—" : `${d}d`),
  pct: (n: number | null) => (n == null ? "—" : `${Math.round(n * 10) / 10}%`),
};

export type CoachCopy = typeof COACH_COPY;
