#!/usr/bin/env python3
"""scaffold-driver.py — auto-create a mock-lane driver STUB the moment a feature's .feature exists.

A new feature's Gherkin spec is authored by Phase 1, but running it on the mock lane needs a driver
(.claude/qa/shared/features/<feature>.cjs) — bespoke code that drives the WhatsApp interactions. That
"how" can't be generated from the spec, but the FILE can be: this emits the @mock-lane marker, the
exports.run skeleton, and one rec() stub per @e2e scenario, so the feature enrols in the mock lane and
the interactions are filled in rather than started from a blank page. Refuses to overwrite an existing
driver (a real driver is never clobbered by a stub).

    python3 scaffold-driver.py <feature> [--force]

Reads  tests/features/whatsapp/niete/<feature>.feature
Writes .claude/qa/shared/features/<feature>.cjs   (only if absent, or --force)
"""
import argparse, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))


def scenarios(feature_path):
    """[(id, name)] for every @e2e scenario, id = <PREFIX><NN> from the feature name."""
    lines = open(feature_path, encoding="utf-8").read().splitlines()
    out, pending_e2e = [], False
    for ln in lines:
        s = ln.strip()
        if s.startswith("@"):
            pending_e2e = "@e2e" in s
        elif s.startswith("Scenario:") and pending_e2e:
            out.append(s[len("Scenario:"):].strip())
            pending_e2e = False
        elif s and not s.startswith("#"):
            pass
    return out


def prefix(feature):
    base = re.sub(r"[^a-z]", "", feature.lower())
    return (base[:3] or "f").upper()


def render(feature, names):
    px = prefix(feature)
    stubs = []
    for i, nm in enumerate(names, 1):
        sid = f"{px}{i:02d}"
        esc = nm.replace("'", "\\'")
        stubs.append(
            f"  // TODO: drive this scenario, then replace BLOCKED with V(<pass?>, {{ ...evidence }}).\n"
            f"  rec('{sid}', '{esc}', 'BLOCKED',\n"
            f"      {{ reason: 'scaffolded stub — implement the mock-lane interaction (see menu.cjs / lesson-plan.cjs)' }}, 0);"
        )
    body = "\n\n".join(stubs) if stubs else \
        "  rec('" + px + "01', 'TODO first scenario', 'BLOCKED', { reason: 'no @e2e scenarios found in the .feature yet' }, 0);"
    return f"""// @mock-lane — mock-capable driver (uses the mock API, not the browser DOM). Its presence enrols this feature in the mock lane; E2E_MOCK_FEATURES is derived from this marker, so there is no hardcoded list.
/* {feature}.feature — SCAFFOLD generated by scaffold-driver.py. Each @e2e scenario has a stub below;
 * fill in the mock-lane interaction and turn the BLOCKED into a V(...) verdict. The mock API is the
 * same one every other driver uses: api.sendWait / api.openList / api.pickRowAndWait / api.upload /
 * api.flowClick / api.fresh (read replies) / api.db(...). Copy patterns from menu.cjs or lesson-plan.cjs.
 * Do NOT reach for the browser DOM (api.ev / window.__wa) — that breaks the mock lane. */
const V = (c, ev) => [c ? 'PASS' : 'FAIL', ev];

exports.run = async ({{ api, rec, sleep }}) => {{
  await api.resetFlow();

{body}
}};
"""


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("feature")
    ap.add_argument("--force", action="store_true", help="overwrite an existing driver (never a real one by accident)")
    a = ap.parse_args(argv)

    feature_path = os.path.join(ROOT, "tests", "features", "whatsapp", "niete", a.feature + ".feature")
    driver_path = os.path.join(ROOT, ".claude", "qa", "shared", "features", a.feature + ".cjs")

    if not os.path.isfile(feature_path):
        print("no spec at %s — author it first (Phase 1 / gherkin-spec-sync)" % os.path.relpath(feature_path, ROOT))
        return 2
    if os.path.isfile(driver_path) and not a.force:
        print("driver already exists: %s (use --force to overwrite — but a real driver should never be clobbered)"
              % os.path.relpath(driver_path, ROOT))
        return 1

    names = scenarios(feature_path)
    open(driver_path, "w", encoding="utf-8").write(render(a.feature, names))
    print("scaffolded %s with %d scenario stub(s). Next: fill in the interactions, then run"
          % (os.path.relpath(driver_path, ROOT), len(names)))
    print("  bash .claude/qa/shared/commit-e2e.sh HEAD --features %s --record-missing   # if it calls vendors" % a.feature)
    return 0


if __name__ == "__main__":
    sys.exit(main())
