#!/usr/bin/env python3
"""scaffold-driver.py — auto-create a mock-lane driver STUB the moment a feature's .feature exists.

A new feature's Gherkin spec is authored by Phase 1, but running it on the mock lane needs a driver
(.claude/qa/shared/features/<feature>.cjs) — bespoke code that drives the WhatsApp interactions. That
"how" can't be generated from the spec, but the FILE can be: this emits the @mock-lane marker, the
exports.run skeleton, and one rec() stub per @e2e scenario, so the feature enrols in the mock lane and
the interactions are filled in rather than started from a blank page. Refuses to overwrite an existing
driver (a real driver is never clobbered by a stub).

    python3 scaffold-driver.py <feature> [--force]

Reads  tests/features/whatsapp/niete/<feature>.feature
Writes .claude/qa/shared/features/<feature>.cjs   (only if absent, or --force)
"""
import argparse, os, re, sys

# Mirrors SCENARIO_ID_RE in validate_specs.py: letters then digits.
ID_TAG_RE = re.compile(r"^[A-Za-z]{1,5}\d{1,3}$")
PRIORITY_TAGS = frozenset({"p0", "p1", "p2", "p3"})

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))


def scenarios(feature_path, px=None):
    """[(id, name)] for every @e2e scenario.

    The id comes from the scenario's OWN tag (`@COA16`) when it has one — that tag is the identity
    that binds it to the driver (bd-bufzl). Positional ids are the fallback for a spec that has not
    been tagged yet, and they are exactly why the tag exists: inserting a scenario renumbers every
    id after it, so yesterday's COA07 silently becomes COA08.
    """
    lines = open(feature_path, encoding="utf-8").read().splitlines()
    out, pending_e2e, pending_id, n = [], False, None, 0
    for ln in lines:
        t = ln.strip()
        if t.startswith("@"):
            tags = t.split()
            pending_e2e = "@e2e" in tags
            # @P1/@P2/@P3 are priority, not identity, and they match the same letters-then-digits
            # shape — so prefer a tag whose letters ARE this feature's prefix, and never take a
            # priority tag as an id.
            want = (px or prefix_for(feature_path)).lower()
            cands = [x[1:] for x in tags
                     if ID_TAG_RE.match(x[1:]) and x[1:].lower() not in PRIORITY_TAGS]
            pending_id = next((c for c in cands if c.lower().startswith(want)), None) \
                or next(iter(cands), None)
        elif (t.startswith("Scenario:") or t.startswith("Scenario Outline:")) and pending_e2e:
            n += 1
            name = t.split(":", 1)[1].strip()
            out.append((pending_id or "%s%02d" % (px or prefix_for(feature_path), n), name))
            pending_e2e, pending_id = False, None
    return out


def prefix_for(feature_path):
    return prefix(os.path.splitext(os.path.basename(feature_path))[0])


def prefix(feature):
    base = re.sub(r"[^a-z]", "", feature.lower())
    return (base[:3] or "f").upper()


def stub(sid, name):
    esc = name.replace("'", "\\'")
    return (

        f"  // TODO: drive this scenario, then replace BLOCKED with V(<pass?>, {{ ...evidence }}).\n"
        f"  rec('{sid}', '{esc}', 'BLOCKED',\n"
        f"      {{ reason: 'scaffolded stub — implement the mock-lane interaction (see menu.cjs / lesson-plan.cjs)' }}, 0);"
    )


def render(feature, pairs):
    px = prefix(feature)
    stubs = [stub(sid, nm) for sid, nm in pairs]
    body = "\n\n".join(stubs) if stubs else \
        "  rec('" + px + "01', 'TODO first scenario', 'BLOCKED', { reason: 'no @e2e scenarios found in the .feature yet' }, 0);"
    return f"""// @mock-lane — mock-capable driver (uses the mock API, not the browser DOM). Its presence enrols this feature in the mock lane; E2E_MOCK_FEATURES is derived from this marker, so there is no hardcoded list.
/* {feature}.feature — SCAFFOLD generated by scaffold-driver.py. Each @e2e scenario has a stub below;
 * fill in the mock-lane interaction and turn the BLOCKED into a V(...) verdict. The mock API is the
 * same one every other driver uses: api.sendWait / api.openList / api.pickRowAndWait / api.upload /
 * api.flowClick / api.fresh (read replies) / api.db(...). Copy patterns from menu.cjs or lesson-plan.cjs.
 * Do NOT reach for the browser DOM (api.ev / window.__wa) — that breaks the mock lane. */
const V = (c, ev) => [c ? 'PASS' : 'FAIL', ev];

exports.run = async ({{ api, rec, sleep }}) => {{
  await api.resetFlow();

{body}
}};
"""


# Any call whose FIRST argument is a scenario-id string literal. Not just `rec(` — coaching.cjs
# records 8 of its 17 scenarios through a `deepOnly(id, name, …)` wrapper, and a checker blind to
# wrappers reports all eight as missing on the day it lands. The id shape does the discriminating,
# so a future wrapper needs no change here.
# Uppercase prefix on purpose: getAttribute('aria-label') and ('data-id') match the same shape
# otherwise, and would surface as phantom scenarios the driver 'records'.
RECORDED_ID_RE = re.compile(r"\b[A-Za-z_$][\w$]*\(\s*'([A-Z]{1,5}(?:\d{1,3}|-[a-z]+))'")


def recorded_ids(driver_path):
    """Every scenario id the driver already records. Read from rec() calls, because that is what the
    runner actually collects — a comment mentioning COA07 proves nothing."""
    return set(RECORDED_ID_RE.findall(open(driver_path, encoding="utf-8").read()))


def sync(driver_path, pairs):
    """Append a stub for each spec scenario the driver does not record. Returns the ids appended.

    NEVER rewrites existing scenario code: the new stubs go in immediately before the closing brace
    of exports.run, and everything above is copied byte for byte. A hand-written driver is worth
    more than any stub, so the only safe edit is an additive one.
    """
    src = open(driver_path, encoding="utf-8").read()
    have = recorded_ids(driver_path)
    missing = [(sid, nm) for sid, nm in pairs if sid not in have]
    if not missing:
        return []
    cut = src.rstrip().rfind("};")
    if cut == -1:
        raise SystemExit("cannot find the end of exports.run in %s — refusing to guess" % driver_path)
    block = ("\n  // ── appended by scaffold-driver.py --sync: these scenarios exist in the .feature\n"
             "  //    but had no driver. Implement each one, then turn BLOCKED into V(...).\n"
             + "\n\n".join(stub(sid, nm) for sid, nm in missing) + "\n\n")
    open(driver_path, "w", encoding="utf-8").write(src[:cut] + block + src[cut:])
    return [sid for sid, _ in missing]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("feature")
    ap.add_argument("--force", action="store_true", help="overwrite an existing driver (never a real one by accident)")
    ap.add_argument("--sync", action="store_true",
                    help="append stubs for spec scenarios the EXISTING driver does not record")
    ap.add_argument("--root", default=ROOT, help="repo root (tests use a throwaway tree)")
    a = ap.parse_args(argv)

    feature_path = os.path.join(a.root, "tests", "features", "whatsapp", "niete", a.feature + ".feature")
    driver_path = os.path.join(a.root, ".claude", "qa", "shared", "features", a.feature + ".cjs")

    if not os.path.isfile(feature_path):
        print("no spec at %s — author it first (Phase 1 / gherkin-spec-sync)" % os.path.relpath(feature_path, a.root))
        return 2

    pairs = scenarios(feature_path, prefix(a.feature))

    if a.sync:
        if not os.path.isfile(driver_path):
            print("no driver at %s — run without --sync to create one"
                  % os.path.relpath(driver_path, a.root))
            return 2
        added = sync(driver_path, pairs)
        if not added:
            print("%s is already in sync with its spec (%d scenario(s))"
                  % (os.path.relpath(driver_path, a.root), len(pairs)))
            return 0
        print("appended %d stub(s) to %s: %s"
              % (len(added), os.path.relpath(driver_path, a.root), ", ".join(added)))
        print("  Each records BLOCKED until you implement it. A stub is NOT coverage.")
        return 0

    if os.path.isfile(driver_path) and not a.force:
        print("driver already exists: %s — use --sync to append the scenarios it is missing "
              "(--force overwrites, but a real driver should never be clobbered)"
              % os.path.relpath(driver_path, a.root))
        return 1

    open(driver_path, "w", encoding="utf-8").write(render(a.feature, pairs))
    print("scaffolded %s with %d scenario stub(s). Next: fill in the interactions, then run"
          % (os.path.relpath(driver_path, a.root), len(pairs)))
    print("  bash .claude/qa/shared/commit-e2e.sh HEAD --features %s" % a.feature)
    return 0


if __name__ == "__main__":
    sys.exit(main())
