/**
 * bd-fmf24g.6 — every word the teacher v2 Assessment screens show (the feature's own copy file).
 *
 * Same rules as the new UI's copy (newui/copy.ts, DESIGN.md): 1–3 words, 4 at most, no sentences, no
 * question marks. English only for now; the Urdu pass gives each key an Urdu value. DATA is not copy:
 * a subject's name, a chapter's title and a question type's name (MCQs, Label the Diagram …) come from
 * the API as they are.
 */

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as const;
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] as const;

export const ASSESSMENT_V2_COPY = {
  title: 'Assessment',
  home: 'Home',
  back: 'Back',
  next: 'Next',
  /* hub */
  newPaper: 'New paper',
  withKey: 'With answer key',
  beingMade: 'Being made',
  myPapers: 'My papers',
  all: 'All',
  noPapersYet: 'No papers yet',
  writing: 'Writing',
  failed: 'Failed',
  grade: (g: number | string) => `Grade ${g}`,
  gradeSubject: (g: number | string, subject: string) => `Grade ${g} · ${subject}`,
  questionsCount: (n: number) => (n === 1 ? '1 question' : `${n} questions`),
  marksCount: (n: number) => (n === 1 ? '1 mark' : `${n} marks`),
  version: (n: number) => `v${n}`,
  versionLong: (n: number) => `Version ${n}`,
  chapterShort: (n: number) => `Ch ${n}`,
  join: (...parts: Array<string | null | undefined | false>) => parts.filter(Boolean).join(' · '),
  /* the new paper's steps */
  step: (n: number, of: number) => `Step ${n} of ${of}`,
  steps: {
    class: 'Class',
    cover: 'Chapters or pages',
    questions: 'Questions',
    types: 'Question types',
    extras: 'Marks and lines',
    check: 'Check and make',
  },
  myClasses: 'My classes',
  allGrades: 'All grades',
  noClasses: 'No classes yet',
  chapters: 'Chapters',
  pages: 'Pages',
  picked: (n: number) => `${n} picked`,
  upTo: (n: number) => `Up to ${n}`,
  bookPages: (n: number) => `Book p.1–${n}`,
  pageRange: (from: number, to: number) => `p. ${from} – ${to}`,
  pagesSpan: (from: number | null, to: number | null) => (from != null && to != null ? `p.${from}–${to}` : ''),
  from: 'From',
  to: 'To',
  addPages: 'Add pages',
  removePages: 'Remove pages',
  howMany: 'How many',
  fewer: 'Fewer',
  more: 'More',
  questions: 'questions',
  fromWhere: 'From where',
  sources: {
    seen: { name: 'From the book', sub: 'Seen' },
    unseen: { name: 'New questions', sub: 'Unseen · same topics' },
    both: { name: 'Mix of both', sub: 'Seen + Unseen' },
  },
  fromBook: 'From the book',
  ofCount: (n: number) => `of ${n}`,
  bookShort: (n: number) => `Book · ${n}`,
  newShort: (n: number) => `New · ${n}`,
  newCount: 'New questions',
  bookCount: 'Book',
  autoMix: 'Auto mix',
  chooseTypes: 'Choose types',
  howManyEach: 'How many each',
  ofTarget: (n: number, of: number) => `${n} of ${of}`,
  objective: 'Objective',
  written: 'Written',
  bookOnly: 'Book questions only',
  totalMarks: 'Total marks',
  optional: 'Optional',
  noLimit: 'No limit',
  setTotal: 'Set total',
  marks: 'marks',
  marksLabel: 'Marks',
  onPaper: 'On the paper',
  answerLines: 'Answer lines',
  on: 'On',
  off: 'Off',
  newPaperCrumb: 'New paper',
  edit: 'Edit',
  file: 'File',
  pdfWithKey: 'PDF + answer key',
  fixed: 'Fixed',
  makePaper: 'Make paper',
  making: 'Starting',
  couldNotStart: 'Not started',
  /* writing / failed / ready */
  writingTitle: 'Writing your paper',
  aboutAMinute: '~1 min',
  safeToLeave: 'Safe to leave',
  slow: 'Taking longer',
  notMadeTitle: 'Paper not made',
  tryAgain: 'Try again',
  changeChoices: 'Change choices',
  dismiss: 'Dismiss',
  readyTitle: 'Paper ready',
  ready: 'Ready',
  download: 'Download',
  answerKey: 'Answer key',
  key: 'Key',
  makeAnother: 'Make another',
  open: 'Open',
  notFoundTitle: 'Paper not found',
  /* paper page */
  versions: 'Versions',
  latest: 'Latest',
  first: 'First',
  noKey: 'No answer key',
  notAvailable: 'Not available',
  couldNotOpen: 'Could not open',
  /* edit */
  editPaper: 'Edit paper',
  kept: (n: number) => `${n} kept`,
  removed: (n: number) => `${n} removed`,
  added: (n: number) => `${n} added`,
  keepQuestion: (n: number | string) => `Keep question ${n}`,
  removeQuestion: (n: number | string) => `Remove question ${n}`,
  addQuestion: 'Add question',
  newQuestion: 'New question',
  close: 'Close',
  cancel: 'Cancel',
  saveAs: (v: number) => `Save as v${v}`,
  saving: 'Saving',
  saved: 'Saved',
  notSaved: 'Not saved',
  nothingChanged: 'Nothing changed',
  question: 'Question',
  questionN: (n: number | string) => `Question ${n}`,
  answer: 'Answer',
  keyOnly: 'Key only',
  lines: 'Lines',
  options: 'Options',
  optionN: (n: number) => `Option ${n}`,
  correct: 'Correct',
  pairs: 'Pairs',
  passage: 'Passage',
  parts: 'Parts',
  partN: (n: number) => `Part ${n}`,
  removeFromPaper: 'Remove question',
  wordN: (n: number) => `Word ${n}`,
  meaningN: (n: number) => `Meaning ${n}`,
  pairA: (n: number) => `Pair ${n} A`,
  pairB: (n: number) => `Pair ${n} B`,
  correctN: (n: number) => `Option ${n} correct`,
  addPart: 'Add part',
  removePart: (n: number) => `Remove part ${n}`,
  removeAdded: (n: number) => `Remove new ${n}`,
  instruction: 'Instruction',
  putBack: 'Put back',
  done: 'Done',
  checking: 'Checking',
  newItem: 'New',
  editingOff: 'Editing off',
  /* loading */
  loadFailed: 'Could not load',
  comingSoon: 'Coming soon',
  nothingHere: 'Nothing here',
  /* failure reasons (the bot's codes, as labels) */
  failures: {
    BOOK_NOT_FOUND: 'No book yet',
    CHAPTER_NOT_FOUND: 'Chapter not found',
    NO_CONTENT: 'No chapter text',
    PAGE_OUT_OF_RANGE: 'Pages outside book',
    INVALID_PAGE_RANGE: 'Wrong pages',
    TRUNCATED: 'Too many questions',
    MODEL_UNAVAILABLE: 'Busy now',
    BAD_JSON: 'Came out wrong',
    NO_QUESTIONS: 'No questions written',
    RENDER_FAILED: 'File not made',
    UPLOAD_FAILED: 'Not saved',
  } as Record<string, string>,
  failureFallback: 'Something went wrong',
  /* days */
  days: {
    today: 'Today',
    yesterday: 'Yesterday',
    date: (weekday: number, day: number, month: number) => `${WEEKDAYS[weekday]} ${day} ${MONTHS[month]}`,
  },
};

export type AssessmentV2Copy = typeof ASSESSMENT_V2_COPY;
