/**
 * Coaching Debrief Config Conformance Tests
 *
 * Guards the single-source-of-truth seam: the number of reflective
 * questions (NUM_REFLECTIVE_QUESTIONS) drives ALL of —
 *   1. the "< N" loop bound in reflective-conversation.service.js,
 *   2. the "question X of N" string in the gpt5-mini meta-prompt,
 *   3. the number of few-shot example arms in that meta-prompt.
 * If someone changes one and not the others, these tests fail.
 *
 * Also asserts the coaching MODEL text (S.T.I.C.K.S.) is sourced from
 * coaching-debrief.config.js, not inlined in gpt5-mini.service.js.
 */

const fs = require('fs');
const path = require('path');

// jsonrepair is a bot-only dependency; CI runs the root test pass before `cd bot && npm ci`,
// so virtual-mock it for the runtime test that loads the real gpt5-mini.service.
jest.mock('jsonrepair', () => ({ jsonrepair: (s) => s }), { virtual: true });

const REPO_ROOT = path.resolve(__dirname, '../..');
const config = require('../../bot/shared/config/coaching-debrief.config');

const reflectiveSrc = fs.readFileSync(
  path.join(REPO_ROOT, 'bot/shared/services/coaching/reflective-conversation.service.js'),
  'utf8'
);
const gpt5Src = fs.readFileSync(
  path.join(REPO_ROOT, 'bot/shared/services/gpt5-mini.service.js'),
  'utf8'
);

describe('coaching-debrief.config — single source of truth', () => {
  test('exports the documented shape', () => {
    expect(config).toHaveProperty('NUM_REFLECTIVE_QUESTIONS');
    expect(config).toHaveProperty('coachingModel');
    expect(config).toHaveProperty('rules');
    expect(config).toHaveProperty('avoid');
    expect(typeof config.NUM_REFLECTIVE_QUESTIONS).toBe('number');
    expect(Array.isArray(config.rules)).toBe(true);
    expect(Array.isArray(config.avoid)).toBe(true);
  });

  test('N is currently 3 (behavior preserved)', () => {
    expect(config.NUM_REFLECTIVE_QUESTIONS).toBe(3);
  });
});

describe('loop bound derives from NUM_REFLECTIVE_QUESTIONS', () => {
  test('reflective-conversation imports the config constant', () => {
    expect(reflectiveSrc).toMatch(
      /require\(['"][^'"]*coaching-debrief\.config['"]\)/
    );
    expect(reflectiveSrc).toContain('NUM_REFLECTIVE_QUESTIONS');
  });

  test('the "< N" loop bound uses the constant, not a literal', () => {
    // The bound must reference the constant.
    expect(reflectiveSrc).toMatch(/questionsAnswered\s*<\s*NUM_REFLECTIVE_QUESTIONS/);
    // And must NOT use a hardcoded "< 3" (the magic number it replaced).
    expect(reflectiveSrc).not.toMatch(/questionsAnswered\s*<\s*3\b/);
  });
});

describe('meta-prompt "of N" string derives from NUM_REFLECTIVE_QUESTIONS', () => {
  test('gpt5-mini imports the config constant', () => {
    expect(gpt5Src).toMatch(
      /require\(['"][^'"]*coaching-debrief\.config['"]\)/
    );
  });

  test('the "question X of N" string interpolates the constant', () => {
    expect(gpt5Src).toMatch(/of \$\{NUM_REFLECTIVE_QUESTIONS\}/);
    // No leftover hardcoded "of 3".
    expect(gpt5Src).not.toMatch(/question \$\{questionNumber\} of 3\b/);
  });
});

describe('few-shot example arm count derives from NUM_REFLECTIVE_QUESTIONS', () => {
  test('arms are generated by iterating NUM_REFLECTIVE_QUESTIONS, not three inline ternaries', () => {
    // The arms must be built from a length-N iteration over the constant.
    expect(gpt5Src).toMatch(/length:\s*NUM_REFLECTIVE_QUESTIONS/);
    // The original three inline arms must be gone.
    expect(gpt5Src).not.toMatch(/questionNumber === 2 && questionConfig\.examples\.question2/);
    expect(gpt5Src).not.toMatch(/questionNumber === 3 && questionConfig\.examples\.question3/);
  });

  test('generateReflectiveQuestion renders exactly one example arm per turn for N turns', async () => {
    // Mock dependencies so we can capture the prompt sent to the model.
    jest.resetModules();
    let capturedPrompt = '';
    jest.doMock('openai', () => {
      return class OpenAI {
        constructor() {
          this.chat = {
            completions: {
              create: async ({ messages }) => {
                capturedPrompt = messages[0].content;
                return {
                  choices: [{ message: { content: 'mock question' } }],
                  usage: { completion_tokens: 1 },
                };
              },
            },
          };
        }
      };
    });
    jest.doMock('../../bot/shared/utils/logger', () => ({ logToFile: jest.fn() }));

    const GPT5MiniService = require('../../bot/shared/services/gpt5-mini.service');
    const { NUM_REFLECTIVE_QUESTIONS } = config;
    const { getLanguageConfig } = require('../../bot/shared/config/language-config');
    const langConfig = getLanguageConfig('en');

    for (let n = 1; n <= NUM_REFLECTIVE_QUESTIONS; n++) {
      capturedPrompt = '';
      await GPT5MiniService.generateReflectiveQuestion({}, [], n, 'some transcript', 'en');

      // "of N" string is present.
      expect(capturedPrompt).toContain(`question ${n} of ${NUM_REFLECTIVE_QUESTIONS}`);

      // The "ADDITIONAL EXAMPLES" block surfaces exactly this turn's example.
      const expectedExample =
        (langConfig.reflectiveQuestions.examples[`question${n}`] ||
          langConfig.reflectiveQuestions.examples.question1).example;
      const block = capturedPrompt.split('ADDITIONAL EXAMPLES OF GOOD QUESTIONS')[1] || '';
      const arms = block.split('\nAVOID:')[0];
      expect(arms).toContain(expectedExample);
    }

    jest.dontMock('openai');
    jest.resetModules();
  });
});

describe('coaching MODEL text is sourced from config, not inlined', () => {
  test('config carries the S.T.I.C.K.S. model description', () => {
    expect(config.coachingModel.name).toBe('S.T.I.C.K.S.');
    expect(config.coachingModel.description).toContain('Specific');
    expect(config.coachingModel.description).toContain('Strength-based');
  });

  test('the S.T.I.C.K.S. model text is NOT hardcoded in gpt5-mini.service.js', () => {
    // The expanded model parenthetical must live in config only.
    expect(gpt5Src).not.toContain(
      'Specific, Timely, Inquiry-based, Collaborative, Kind, Strength-based'
    );
  });

  test('gpt5-mini renders rules and avoid lists from config arrays', () => {
    expect(gpt5Src).toMatch(/rules\.map/);
    expect(gpt5Src).toMatch(/avoid\.map/);
    // The old inline numbered rules / dashed avoid lines must be gone.
    expect(gpt5Src).not.toContain('1. YOU MUST quote actual dialogue from the transcript');
    expect(gpt5Src).not.toContain('- Starting with "Reflecting on your lesson..."');
  });
});
