/**
 * bd-4404s7.5 — every word the coach Reports screens show, in the area's own copy file: Recent and All
 * observations, the observation page, and the four screens of the observation (Feedback Form, Debrief, Your
 * feedback, Send {name} the report).
 *
 * Bilingual from day one: REPORTS = { en, ur }, read with useCopy(REPORTS) (teacher/i18n); `ur` is typed to
 * en's exact SHAPE, so a missing key fails the build. The Urdu is MACHINE-DRAFTED (words from the spec's
 * COACH.md §5, the bot's observe-strings.js and the ontology) and awaits a native check
 * (workbench/teacher-v2-impl/urdu-review/urdu-review.tsv, verdict NATIVE-CHECK).
 *
 * Same rules as the kit's copy: labels of 1-4 words, no sentences. DATA is not copy: a teacher's name, a school,
 * the form's indicator names and ratings, the guide and the feedback text come from the API as they are.
 */

import { bilingual, type Bilingual, type Words } from "../../teacher/i18n";

export const REPORTS_EN = {
  title: "Reports",
  observe: "Observe",
  back: "Back",
  loadFailed: "Could not load",
  retry: "Try again",
  dash: "—",

  /* the list */
  reportsWaiting: (n: number) => (n === 1 ? "1 report waiting" : `${n} reports waiting`),
  waitingForYou: "Waiting for you",
  inProgress: "In progress",
  recent: "Recent Observations",
  allTitle: "All Observations",
  allReports: "All reports",
  noObservations: "No observations yet",
  noneInRange: "None in these dates",
  searchPlaceholder: "Name or phone",
  analysing: "Analysing",
  /** The four labelled segments under a card (Analysed, Feedback Form, Debrief, Sent). */
  segments: ["Analysed", "Feedback Form", "Debrief", "Sent"],
  /** The chip on a row, by where it is. */
  chip: { analysing: "Analysing", draft: "Feedback Form", talk: "Debrief", report: "Send report", sent: "Sent" },
  kpiObservations: "Observations",
  kpiAvg: "Avg. HITL Score",
  kpiWaiting: "Waiting for you",
  kpiSent: "Sent",

  /* the observation page */
  observation: "Observation",
  dcScore: "Digital Coach score",
  dcScoreOf: (n: string) => `Digital Coach score ${n}`,
  draftBeforeCheck: "Draft before your check",
  finalScore: (n: string) => `Final score ${n}`,
  steps: "Steps",
  stepAnalysed: "Observation analysed",
  stepForm: "Feedback Form",
  stepDebrief: "Debrief",
  stepFeedback: "Your feedback",
  stepSend: (name: string) => `Send ${name} the report`,
  yourTurn: "Your turn",
  onWhatsApp: "On WhatsApp",
  working: "Working",
  continueOnWhatsApp: "Continues on WhatsApp",
  stopped: "Observation stopped",
  whatYouMade: "What you made",
  formRowSub: "Your ratings",
  debriefRowSub: "Guide and your talk",
  feedbackRowSub: "From the Digital Coach",
  reportReceived: (name: string) => `The report ${name} received`,
  reportSentOn: (when: string) => `Report sent · ${when}`,
  reportImage: (name: string) => `${name}’s report`,

  /* the Feedback Form */
  formTitle: "Feedback Form",
  stepCrumb: (name: string, n: number, total: number) => `${name} · Step ${n} of ${total}`,
  partOf: (n: number, total: number) => `Part ${n} of ${total}`,
  legendYours: "Your rating",
  legendDc: "Digital Coach",
  na: "N/A",
  ratingOf: (id: string) => `Rating for ${id}`,
  whatSeen: "What was seen",
  verdict: "Verdict",
  toImprove: "To improve",
  changedFrom: (was: string) => `Changed from ${was}`,
  moveOf: (k: number, n: number) => `Move ${k} of ${n}`,
  fromPlan: "From the lesson plan",
  next: "Next part",
  saveForm: "Save",
  saveTitle: "Save Feedback Form",
  noChanges: "No changes",
  changesSummary: (ratings: number, notes: number) => `${ratings} ratings, ${notes} notes changed`,
  saveContinue: "Save and continue",
  keepChecking: "Keep checking",
  saving: "Saving",
  saveFailed: "Could not save",
  notEditable: "Cannot change it now",
  readOnly: "Your answers",

  /* the Debrief */
  debriefTitle: "Debrief",
  aboutTenMinutes: "~10 min",
  afterClass: "After class",
  wentWell: "Went well",
  toGrow: "One thing to grow",
  oneAction: "One action",
  askLast: "Ask this last",
  writingGuide: "Writing your guide",
  guideFailed: "Guide did not load",
  saveFormFirst: "Save the form first",
  startRecording: "Start recording",
  uploadRecording: "Upload recording",
  yourDebrief: "Your debrief",
  debriefWith: (name: string) => `Your debrief with ${name}`,
  listeningTalk: "Listening to your talk",
  notAudio: "Not a recording",
  tooLarge: "File too large",
  sendingTalk: "Sending",
  netTitle: "The internet stopped",
  netSafe: "The recording is safe",
  refused: "Not accepted",
  micBlocked: "Microphone blocked",
  keepOpenSending: "Keep this screen open",
  micHelpApp: "Open phone Settings, Apps, NIETE, Permissions, Microphone, Allow.",
  micHelpWeb: "Tap the lock by the web address, then allow the microphone.",
  /** The recorder's own lines (components/coaching/coach/CoachRecorder). */
  recorder: {
    hearing: "We can hear you both.",
    keepOpen: "Keep this screen open. Put the phone between the two of you.",
    shortNote: "That is short. A few minutes of talking gives better feedback.",
  },
  problems: {
    too_short: "Recording too short",
    failed: "Could not listen",
    feedback_failed: "No feedback yet",
    duplicate: "Recording already used",
  },

  /* Your feedback */
  feedbackTitle: "Your feedback",
  youDidWell: "You did well",
  tryNext: "Try next time",
  askYourself: "Ask yourself",
  concern: "Look at this",
  feedbackWaiting: "Feedback is being written",
  nextStep: "Next",

  /* Send {name} the report */
  sendTitle: (name: string) => `Send ${name} the report`,
  preview: "Preview",
  to: "To",
  sendTo: (name: string) => `Send to ${name}`,
  making: "Making the report",
  sendFailed: "Report not sent",
  sending: "Sending",
  sentTitle: (name: string) => `Sent to ${name}`,
  waitingTeacher: (name: string) => `Waiting for ${name}`,
  notNow: "Not now",
  openReport: "Open report",
  pct: (n: number | null) => (n == null ? "—" : `${Math.round(n * 10) / 10}%`),
};

export const REPORTS_UR: Words<typeof REPORTS_EN> = {
  title: "رپورٹس",
  observe: "مشاہدہ",
  back: "واپس",
  loadFailed: "لوڈ نہیں ہو سکا",
  retry: "دوبارہ کوشش کریں",
  dash: "—",

  reportsWaiting: (n: number) => (n === 1 ? "1 رپورٹ منتظر" : `${n} رپورٹیں منتظر`),
  waitingForYou: "آپ کے منتظر",
  inProgress: "جاری",
  recent: "حالیہ مشاہدات",
  allTitle: "تمام مشاہدات",
  allReports: "تمام رپورٹس",
  noObservations: "ابھی کوئی مشاہدہ نہیں",
  noneInRange: "ان تاریخوں میں نہیں",
  searchPlaceholder: "نام یا فون",
  analysing: "تجزیہ جاری",
  segments: ["تجزیہ ہو گیا", "فیڈبیک فارم", "ڈی بریف", "بھیجی گئی"],
  chip: { analysing: "تجزیہ جاری", draft: "فیڈبیک فارم", talk: "ڈی بریف", report: "رپورٹ بھیجیں", sent: "بھیجی گئی" },
  kpiObservations: "مشاہدات",
  kpiAvg: "اوسط HITL اسکور",
  kpiWaiting: "آپ کے منتظر",
  kpiSent: "بھیجی گئیں",

  observation: "مشاہدہ",
  dcScore: "ڈیجیٹل کوچ اسکور",
  dcScoreOf: (n: string) => `ڈیجیٹل کوچ اسکور ${n}`,
  draftBeforeCheck: "جانچ سے پہلے مسودہ",
  finalScore: (n: string) => `حتمی اسکور ${n}`,
  steps: "مراحل",
  stepAnalysed: "مشاہدے کا تجزیہ",
  stepForm: "فیڈبیک فارم",
  stepDebrief: "ڈی بریف",
  stepFeedback: "آپ کا فیڈبیک",
  stepSend: (name: string) => `${name} کو رپورٹ بھیجیں`,
  yourTurn: "آپ کی باری",
  onWhatsApp: "واٹس ایپ پر",
  working: "جاری",
  continueOnWhatsApp: "آگے واٹس ایپ پر",
  stopped: "مشاہدہ روک دیا گیا",
  whatYouMade: "آپ نے بنایا",
  formRowSub: "آپ کی ریٹنگز",
  debriefRowSub: "گائیڈ اور گفتگو",
  feedbackRowSub: "ڈیجیٹل کوچ سے",
  reportReceived: (name: string) => `${name} کو ملی رپورٹ`,
  reportSentOn: (when: string) => `رپورٹ بھیجی گئی · ${when}`,
  reportImage: (name: string) => `${name} کی رپورٹ`,

  formTitle: "فیڈبیک فارم",
  stepCrumb: (name: string, n: number, total: number) => `${name} · مرحلہ ${n} از ${total}`,
  partOf: (n: number, total: number) => `حصہ ${n} از ${total}`,
  legendYours: "آپ کی ریٹنگ",
  legendDc: "ڈیجیٹل کوچ",
  na: "لاگو نہیں",
  ratingOf: (id: string) => `${id} کی ریٹنگ`,
  whatSeen: "جو دیکھا گیا",
  verdict: "نتیجہ",
  toImprove: "بہتری کے لیے",
  changedFrom: (was: string) => `پہلے ${was} تھا`,
  moveOf: (k: number, n: number) => `طریقہ ${k} از ${n}`,
  fromPlan: "لیسن پلان سے",
  next: "اگلا حصہ",
  saveForm: "محفوظ کریں",
  saveTitle: "فارم محفوظ کریں",
  noChanges: "کوئی تبدیلی نہیں",
  changesSummary: (ratings: number, notes: number) => `${ratings} ریٹنگ، ${notes} نوٹ بدلے`,
  saveContinue: "محفوظ کریں اور آگے",
  keepChecking: "جانچتے رہیں",
  saving: "محفوظ ہو رہا ہے",
  saveFailed: "محفوظ نہیں ہوا",
  notEditable: "اب بدل نہیں سکتا",
  readOnly: "آپ کے جوابات",

  debriefTitle: "ڈی بریف",
  aboutTenMinutes: "تقریباً 10 منٹ",
  afterClass: "کلاس کے بعد",
  wentWell: "اچھا ہوا",
  toGrow: "بہتری کا ایک نکتہ",
  oneAction: "ایک عمل",
  askLast: "آخر میں پوچھیں",
  writingGuide: "گائیڈ بن رہی ہے",
  guideFailed: "گائیڈ لوڈ نہیں ہوئی",
  saveFormFirst: "پہلے فارم محفوظ کریں",
  startRecording: "ریکارڈنگ شروع کریں",
  uploadRecording: "ریکارڈنگ اپ لوڈ کریں",
  yourDebrief: "آپ کا ڈی بریف",
  debriefWith: (name: string) => `${name} سے ڈی بریف`,
  listeningTalk: "گفتگو کا تجزیہ",
  notAudio: "یہ ریکارڈنگ نہیں",
  tooLarge: "فائل بہت بڑی ہے",
  sendingTalk: "بھیجا جا رہا ہے",
  netTitle: "انٹرنیٹ بند ہو گیا",
  netSafe: "ریکارڈنگ محفوظ ہے",
  refused: "قبول نہیں ہوا",
  micBlocked: "مائیک کی اجازت نہیں",
  keepOpenSending: "یہ اسکرین کھلی رکھیں",
  micHelpApp: "فون کی سیٹنگز میں NIETE کے لیے مائیکروفون کی اجازت دیں۔",
  micHelpWeb: "ویب ایڈریس کے ساتھ تالے پر ٹیپ کریں، پھر مائیکروفون کی اجازت دیں۔",
  recorder: {
    hearing: "ہم آپ دونوں کو سن رہے ہیں۔",
    keepOpen: "یہ اسکرین کھلی رکھیں۔ فون دونوں کے بیچ رکھیں۔",
    shortNote: "یہ مختصر ہے۔ چند منٹ کی گفتگو سے بہتر فیڈبیک ملتا ہے۔",
  },
  problems: {
    too_short: "ریکارڈنگ بہت چھوٹی",
    failed: "سنا نہیں جا سکا",
    feedback_failed: "فیڈبیک ابھی نہیں بنا",
    duplicate: "ریکارڈنگ پہلے استعمال ہوئی",
  },

  feedbackTitle: "آپ کا فیڈبیک",
  youDidWell: "آپ نے اچھا کیا",
  tryNext: "اگلی بار آزمائیں",
  askYourself: "خود سے پوچھیں",
  concern: "غور طلب بات",
  feedbackWaiting: "فیڈبیک بن رہا ہے",
  nextStep: "اگلا",

  sendTitle: (name: string) => `${name} کو رپورٹ بھیجیں`,
  preview: "پیش منظر",
  to: "کو",
  sendTo: (name: string) => `${name} کو بھیجیں`,
  making: "رپورٹ بن رہی ہے",
  sendFailed: "رپورٹ نہیں بھیجی گئی",
  sending: "بھیجا جا رہا ہے",
  sentTitle: (name: string) => `${name} کو بھیجی`,
  waitingTeacher: (name: string) => `${name} کا انتظار`,
  notNow: "ابھی نہیں",
  openReport: "رپورٹ کھولیں",
  pct: (n: number | null) => (n == null ? "—" : `${Math.round(n * 10) / 10}%`),
};

export const REPORTS = bilingual(REPORTS_EN, REPORTS_UR);
export type ReportsCopy = Words<typeof REPORTS_EN>;

/** Registered for the completeness test beside it (the teacher registry's glob covers only teacher/*). */
export const COPY_ENTRY = {
  screen: "Coach · Reports",
  module: REPORTS as Bilingual<unknown>,
  /** "—" and the percent formatter are rightly the same in both languages. */
  same: ["dash", "pct"],
  /** Sentences that mirror a screen's name word for word. */
  longOk: ["reportReceived", "stepSend", "changesSummary", "stepCrumb", "micHelp", "recorder"],
};
