BEGIN;
-- bd-2233: answers table columns for open-ended capstone answers (nullable, additive)
ALTER TABLE training_assessment_answers ADD COLUMN IF NOT EXISTS answer_text text;
ALTER TABLE training_assessment_answers ADD COLUMN IF NOT EXISTS answer_score smallint;
ALTER TABLE training_assessment_answers ADD COLUMN IF NOT EXISTS feedback_text text;
-- widen chosen_option for multi-select sets on 10-option questions (defensive)
ALTER TABLE training_assessment_answers ALTER COLUMN chosen_option TYPE varchar(32);

-- bd-2233: BH capstone grand-quiz rows (quiz_type='capstone' keeps every MCQ path inert)
INSERT INTO training_grand_quizzes (level_id, source_quiz_id, quiz_type, is_active) SELECT 18, 8, 'capstone', true WHERE NOT EXISTS (SELECT 1 FROM training_grand_quizzes WHERE source_quiz_id=8 AND quiz_type='capstone');
INSERT INTO training_grand_quizzes (level_id, source_quiz_id, quiz_type, is_active) SELECT 19, 9, 'capstone', true WHERE NOT EXISTS (SELECT 1 FROM training_grand_quizzes WHERE source_quiz_id=9 AND quiz_type='capstone');
INSERT INTO training_grand_quizzes (level_id, source_quiz_id, quiz_type, is_active) SELECT 20, 10, 'capstone', true WHERE NOT EXISTS (SELECT 1 FROM training_grand_quizzes WHERE source_quiz_id=10 AND quiz_type='capstone');
INSERT INTO training_grand_quizzes (level_id, source_quiz_id, quiz_type, is_active) SELECT 21, 11, 'capstone', true WHERE NOT EXISTS (SELECT 1 FROM training_grand_quizzes WHERE source_quiz_id=11 AND quiz_type='capstone');

-- bd-2233: the open-ended questions (empty options + empty correct_option = open-ended)
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4217, 'Define your Lesson Objective. Choose one English Language Teaching (ELT) topic from your syllabus (e.g., Subject–Verb Agreement, Descriptive Paragraph Writing, or Active Listening). Identify a clear Lesson Objective based on a related SLO from the National Curriculum that describes what the student will be able to do with the language. Your objective must use a clear action verb that targets a specific language skill (e.g., Summarize a story, Apply past tense in a role-play, or Analyze Tier 2 vocabulary).', '[]'::jsonb, '', 1, true FROM training_grand_quizzes g WHERE g.source_quiz_id=8 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4217);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4218, 'Write your AI Prompt. Use an AI tool to help you brainstorm lesson ideas or generate classroom content (such as a reading passage or a role-play script) that matches your objective. Show the exact prompt you used. It must follow the Role + Task + Context + Output Format formula.', '[]'::jsonb, '', 2, true FROM training_grand_quizzes g WHERE g.source_quiz_id=8 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4218);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4219, 'Describe one activity for your lesson using a Modern Pedagogy. The activity must directly build toward the Lesson Objective you set in Question 1. Choose one or a mix of: Task-Based Learning (TBL) where students complete a meaningful task focusing on meaning before grammar; Communicative Language Teaching (CLT) where students interact in real-life scenarios; or Three-Stage Reading Approach moving through Pre-Reading, While-Reading, and Post-Reading stages.', '[]'::jsonb, '', 3, true FROM training_grand_quizzes g WHERE g.source_quiz_id=8 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4219);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4220, 'Design a Performance Assessment task that requires students to perform a language skill. This must be non-quiz based and reflect a real-life communicative task. Examples: writing an advertisement, telling a story, or participating in a debate. The task must directly measure the objective you wrote in Question 1.', '[]'::jsonb, '', 4, true FROM training_grand_quizzes g WHERE g.source_quiz_id=8 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4220);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4221, 'Design an Analytic Rubric to evaluate the performance task from Question 4. Your rubric must break performance into separate criteria (e.g., Content, Language, Delivery) and include clear descriptors for at least three levels: Outstanding, Successful, and Needs Improvement.', '[]'::jsonb, '', 5, true FROM training_grand_quizzes g WHERE g.source_quiz_id=8 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4221);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4222, 'Convert your rubric into a Student-Facing Success Scale using "I Can..." statements. Use the "I Can..." format so students understand what success looks like and can take ownership of their progress. Each statement should correspond to a level in your rubric.', '[]'::jsonb, '', 6, true FROM training_grand_quizzes g WHERE g.source_quiz_id=8 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4222);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4223, 'In 3–4 sentences, explain how you ensured your activity and assessment directly support your Lesson Objective. Explain why this is a "matched" lesson — how does the performance task prove students met the objective?', '[]'::jsonb, '', 7, true FROM training_grand_quizzes g WHERE g.source_quiz_id=8 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4223);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4224, 'Briefly state one action you took to ensure the AI''s output was safe and accurate for your classroom. Mention how you verified facts, checked for cultural or regional bias, or ensured student privacy was protected.', '[]'::jsonb, '', 8, true FROM training_grand_quizzes g WHERE g.source_quiz_id=8 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4224);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4225, 'Choose one mathematics topic covered in this course (e.g., Number Theory, Angle Measurement, Statistics, or Fractions). Select a related Student Learning Outcome (SLO) from the National Curriculum and break it down into 3–4 clear Lesson Objectives. Each objective must use an action verb from the Revised Bloom''s Taxonomy.', '[]'::jsonb, '', 1, true FROM training_grand_quizzes g WHERE g.source_quiz_id=9 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4225);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4226, 'Use an AI tool to help you brainstorm unstructured lesson ideas or strategic hints that match your objective. Show the exact prompt you used. It must follow the Role + Task + Context + Output Format formula.', '[]'::jsonb, '', 2, true FROM training_grand_quizzes g WHERE g.source_quiz_id=9 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4226);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4227, 'Describe one activity for your lesson using a Modern Pedagogy. The activity must directly build toward the Lesson Objective. Choose one or a mix of: Unstructured Activity (students decide what information is relevant and choose their own solution strategies), Collaborative Learning (students work in teams using Ground Rules for Discussion to foster Exploratory Talk), or Inquiry-Based Learning (students investigate a What-If scenario, e.g., "What happens to area if the radius doubles?").', '[]'::jsonb, '', 3, true FROM training_grand_quizzes g WHERE g.source_quiz_id=9 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4227);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4228, 'Define the final performance task students must complete to prove they have met the objective. Describe a Performance Task (e.g., creating a poster, presenting a reasoning-based solution, or designing a geometric model). Avoid standard MCQs; focus on higher-order thinking where students must justify their answers.', '[]'::jsonb, '', 4, true FROM training_grand_quizzes g WHERE g.source_quiz_id=9 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4228);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4229, 'Design a Qualitative Assessment Rubric to evaluate the performance task from Question 4. Select 2–3 key criteria (e.g., Mathematical Reasoning, Accuracy, Explanation). Use 3 performance levels: Strong, Developing, Emerging. Write clear descriptors for each level. Include feedback that helps students understand how to improve.', '[]'::jsonb, '', 5, true FROM training_grand_quizzes g WHERE g.source_quiz_id=9 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4229);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4230, 'In 3–4 sentences, explain how your activity and assessment directly support your Lesson Objective. Why is this a "matched" lesson?', '[]'::jsonb, '', 6, true FROM training_grand_quizzes g WHERE g.source_quiz_id=9 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4230);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4231, 'Briefly state one action you took to ensure the AI''s output was safe and accurate for your classroom. Mention how you verified facts, checked for cultural bias, or ensured no student privacy was shared with the tool.', '[]'::jsonb, '', 7, true FROM training_grand_quizzes g WHERE g.source_quiz_id=9 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4231);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4232, 'Review your full submission. Describe how you have organized each section and ensured it is complete, concise, and easy to follow.', '[]'::jsonb, '', 8, true FROM training_grand_quizzes g WHERE g.source_quiz_id=9 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4232);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4233, 'Choose one Computer Science topic from your syllabus. Select a related SLO from the National Curriculum and break it down into 3–4 clear Lesson Objectives. Each objective must use an action verb from the Revised Bloom''s Taxonomy (e.g., Identify, Apply, Analyze, Design, Evaluate).', '[]'::jsonb, '', 1, true FROM training_grand_quizzes g WHERE g.source_quiz_id=10 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4233);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4234, 'Use an AI tool to help you brainstorm lesson ideas that match your objective. Show the exact prompt you used. It must follow the Role + Task + Context + Output Format formula.', '[]'::jsonb, '', 2, true FROM training_grand_quizzes g WHERE g.source_quiz_id=10 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4234);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4235, 'Describe one activity for your lesson using a Modern Pedagogy. The activity must directly build toward the Lesson Objective. Choose one or a mix of: Active Learning (students act out or do the concept), Collaborative Learning (students work in structured teams), or Inquiry-Based Learning (students investigate a What-If scenario to test how a system works).', '[]'::jsonb, '', 3, true FROM training_grand_quizzes g WHERE g.source_quiz_id=10 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4235);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4236, 'Define the final performance task students must complete to prove they have met the objective. Describe a Performance Task such as a short coding challenge, a completed flowchart, or a debugging exercise. This task must measure the exact same skill defined in your objectives. Avoid MCQs or recall-based questions.', '[]'::jsonb, '', 4, true FROM training_grand_quizzes g WHERE g.source_quiz_id=10 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4236);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4237, 'Translate your teacher-level assessment criteria into a Student-Facing Success Scale. Use the "I Can..." format so students understand what success looks like and can take ownership of their progress. Write 3–4 statements. Example: Instead of "Student uses correct syntax", write "I can find and fix small errors when my code doesn''t run".', '[]'::jsonb, '', 5, true FROM training_grand_quizzes g WHERE g.source_quiz_id=10 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4237);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4238, 'In 3–4 sentences, explain how you ensured your activity and assessment directly support your Lesson Objective, and how your lesson objective aligns with your SLO. Why is this a "matched" lesson?', '[]'::jsonb, '', 6, true FROM training_grand_quizzes g WHERE g.source_quiz_id=10 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4238);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4240, 'Review your full submission. Describe how you have organized each section and ensured it is complete, concise, and easy to follow. Is anything missing or unclear?', '[]'::jsonb, '', 7, true FROM training_grand_quizzes g WHERE g.source_quiz_id=10 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4240);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4241, 'Before designing your lesson, use an AI tool to help brainstorm activities or draft your rubric. Write a Refined Prompt using the Role + Task + Context + Output Format formula. Then show at least one Iterative Refinement: if the first response was too vague, show how you asked the AI to "revise, simplify, or improve the output" to better fit a large classroom or specific student needs.', '[]'::jsonb, '', 1, true FROM training_grand_quizzes g WHERE g.source_quiz_id=11 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4241);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4242, 'Describe the Problem Definition for your lesson (the Ask Stage of the Engineering Design Process). Identify the real-world problem students will solve and the specific constraints they must work within.', '[]'::jsonb, '', 2, true FROM training_grand_quizzes g WHERE g.source_quiz_id=11 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4242);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4243, 'Describe your full Engineering Design Process (EDP) Implementation Plan covering all 5 stages: Ask (identify problem and constraints), Imagine & Plan (research, brainstorm, sketch designs), Create (build prototype using low-cost materials), Test (gather data on how well the design works), and Improve (mandatory feedback and fix stage using test results). For each stage, describe what students will DO and what the output will be.', '[]'::jsonb, '', 3, true FROM training_grand_quizzes g WHERE g.source_quiz_id=11 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4243);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4244, 'Describe the hands-on activity where students actively design, build, and test a prototype. What low-cost materials will they use? How are students actively engaged in the engineering process rather than just watching?', '[]'::jsonb, '', 4, true FROM training_grand_quizzes g WHERE g.source_quiz_id=11 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4244);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4245, 'Design a Conceptual Exit Ticket to be used after the Test stage of the EDP. Write one higher-order question that asks students to explain a phenomenon related to their design (not just recall a definition). This question should help you identify gaps in scientific reasoning before students move to the Improve stage.', '[]'::jsonb, '', 5, true FROM training_grand_quizzes g WHERE g.source_quiz_id=11 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4245);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4246, 'Describe how you will use the Exit Ticket responses to provide actionable feedback. Rather than marking answers "wrong", how will you prompt students toward the correct scientific principle before they move to the Improve stage?', '[]'::jsonb, '', 6, true FROM training_grand_quizzes g WHERE g.source_quiz_id=11 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4246);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4247, 'Describe the Summative Assessment for your unit. Students must present their final improved prototype along with a Model-Based Explanation. They must justify their final design choices using evidence collected during the Test stage. Assessment should focus on the entire design cycle, including how students managed failure and iteration.', '[]'::jsonb, '', 7, true FROM training_grand_quizzes g WHERE g.source_quiz_id=11 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4247);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4248, 'Explain how your formative assessment (Exit Ticket) and summative assessment (Performance Task) are aligned to the EDP stages, especially the Test → Improve cycle. How do your assessments measure learning from the engineering process, not just the final product?', '[]'::jsonb, '', 8, true FROM training_grand_quizzes g WHERE g.source_quiz_id=11 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4248);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4249, 'Create an original Analytic Rubric for your summative performance task. Select 3–5 dimensions of performance (e.g., Scientific Accuracy, Design Reasoning, Iterative Improvement, Use of Evidence). Create 3–4 performance levels (e.g., Beginning, Proficient, Advanced). Write specific, observable descriptors for each cell — avoid vague terms like "good".', '[]'::jsonb, '', 9, true FROM training_grand_quizzes g WHERE g.source_quiz_id=11 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4249);
INSERT INTO training_questions (grand_quiz_id, source_question_id, question_text, options, correct_option, order_index, is_active) SELECT g.id, 4250, 'Describe your plan to share this rubric with students BEFORE the task begins. How will you use it to support student understanding and ownership of the task expectations?', '[]'::jsonb, '', 10, true FROM training_grand_quizzes g WHERE g.source_quiz_id=11 AND g.quiz_type='capstone' AND NOT EXISTS (SELECT 1 FROM training_questions WHERE source_question_id=4250);
COMMIT;
SELECT g.level_id, count(q.id) AS questions FROM training_grand_quizzes g LEFT JOIN training_questions q ON q.grand_quiz_id=g.id WHERE g.quiz_type='capstone' GROUP BY 1 ORDER BY 1;
