/**
 * bd-s1oo0.7 — every coach-facing word on the child-test page, Urdu first.
 *
 * The coach reads these; the CHILD reads only the card (its language is the
 * block's, not the coach's). Wording is gender-neutral in both languages —
 * Urdu uses passive or plural-neutral forms ("نہیں پڑھی جا رہی") instead of a
 * gendered verb ending. Both languages must carry every key (copy.test.ts).
 */

export type Lang = "ur" | "en";

const en = {
  title: "Child test",
  lang: "اردو",
  back: "Back",
  loading: "Loading…",
  loadFailed: "Could not load. Check the internet and try again.",
  tryAgain: "Try again",
  notAvailable: "The child test is not on for your account yet.",
  noRecorder: "This phone cannot record here. Update the NIETE app, or use the child test on WhatsApp.",
  chooseVisit: "Which visit?",
  noVisit: "No observation today yet. Start the observation on WhatsApp first.",
  visitAt: (time: string) => `Observation at ${time}`,
  todaysChildren: "Today's children",
  listNote: "Rumi chose these children. Test them in this order.",
  grade: (n: number) => `Grade ${n}`,
  roll: (r: string) => `Roll no. ${r}`,
  role: { new: "New", returning: "Returning" },
  status: { listed: "Not tested", tested: "Tested", absent: "Absent", refused: "Refused", absent_final: "Absent", pending: "Not tested" },
  alternates: "If a child is absent, Rumi adds the next one:",
  noClassList: "This school has no Grade 3 or Grade 5 class list yet.",
  frameExhausted: "Every child in this grade has been tested this quarter.",
  isHere: "Is this child here?",
  present: "Present — start",
  absent: "Absent",
  refused: "Does not want to",
  continue: "Continue",
  blocks: { urdu: "Urdu", english: "English", maths: "Maths" },
  step: (i: number, n: number) => `Part ${i} of ${n}`,
  turnPhone: "Turn the phone to the child.",
  sayCue: (cue: string) => `Say «${cue}», then tap Start.`,
  sayCueMaths: "Ask the child to read the numbers. Tap Start first.",
  start: "Start",
  stop: "Stop",
  childFinished: "Child finished",
  childFinishedMaths: "Child finished",
  cantRead: "Cannot read line 1",
  timeUp: "Time is up",
  secondsLeft: "seconds",
  recordingOn: "Recording",
  afterStory: "Now ask the questions. Then the first sounds and the made-up words.",
  ask: "Ask",
  firstSoundOf: "First sound of",
  madeUpWords: "Made-up words (the child reads)",
  fallbackTitle: "Letters, then words",
  numbersTitle: "Numbers",
  startSums: "Start quick sums",
  sumsTitle: "Quick sums",
  stripNow: "Give the child the paper strip, then tap Stop.",
  stopRule: "Stop after 4 wrong in a row.",
  recorded: (t: string) => `Recorded ${t}`,
  listen: "Listen",
  recordAgain: "Record again",
  send: "Send",
  next: "Next",
  photoTitle: "Photo of the maths strip",
  photoSub: "When the child has finished writing. Keep the whole strip in the photo.",
  takePhoto: "Take photo",
  retakePhoto: "Take again",
  noPhoto: "No strip photo",
  sending: "Sending…",
  sent: "Sent",
  savedOnPhone: "Saved on this phone. It will send when the internet is back.",
  notSent: "Not sent.",
  refusedBy: (reason: string) => `Rumi did not accept this (${reason}).`,
  micBlocked: "The microphone cannot be used. Allow it in the phone settings.",
  micAllow: "When the phone asks, tap Allow.",
  unsent: (n: number) => `${n} waiting to send`,
  sendNow: "Send now",
  checkTitle: "What Rumi heard",
  check: "Check",
  marking: "Marks are being prepared…",
  markFailed: "Rumi could not mark this part. Please mark it yourself.",
  waitingMedia: "Waiting for the recording.",
  wordsCorrect: "Words read correctly in 60 seconds",
  heardWrong: "Rumi heard these words wrong. Untick a word the child read right.",
  notSure: "Rumi is not sure about these. Tick a word the child read wrong.",
  correct: "Correct",
  wrong: "Wrong",
  noAnswer: "No answer",
  rumiThinks: (x: string) => `Rumi thinks: ${x}`,
  rumiUnsure: "Rumi unsure — please check",
  rumiUnsureBanner: "Rumi filled in everything it marked. Please check the fields marked “Rumi unsure”.",
  questions: "Questions",
  firstSounds: "First sounds",
  nonwords: "Made-up words",
  fallbackLetters: "Letters correct (of 10)",
  fallbackWords: "Words correct (of 10)",
  numbers: "Numbers",
  quickSumsCorrect: "Quick sums correct",
  written: "Written sums (from the photo)",
  answerRead: (a: string) => `answer read: ${a}`,
  wordProblem: "Word problem",
  saveCheck: "Save",
  saved: "Saved",
  fillAll: "Please answer every item.",
  saveFailed: "Not saved. Please try again.",
  childDone: "Back to the list",
  checkLater: "Check later",
  allChecked: "All checked",
};

type Copy = typeof en;

const ur: Copy = {
  title: "بچوں کا ٹیسٹ",
  lang: "English",
  back: "واپس",
  loading: "لوڈ ہو رہا ہے…",
  loadFailed: "لوڈ نہیں ہوا۔ انٹرنیٹ دیکھیں اور دوبارہ کوشش کریں۔",
  tryAgain: "دوبارہ کوشش",
  notAvailable: "بچوں کا ٹیسٹ ابھی آپ کے اکاؤنٹ پر دستیاب نہیں۔",
  noRecorder: "اس فون پر یہاں ریکارڈنگ نہیں ہو سکتی۔ NIETE ایپ اپڈیٹ کریں، یا واٹس ایپ پر ٹیسٹ کریں۔",
  chooseVisit: "کون سا دورہ؟",
  noVisit: "آج ابھی کوئی مشاہدہ نہیں ہوا۔ پہلے واٹس ایپ پر مشاہدہ شروع کریں۔",
  visitAt: (time: string) => `مشاہدہ ${time}`,
  todaysChildren: "آج کے بچے",
  listNote: "یہ بچے رومی نے چنے ہیں۔ اسی ترتیب سے ٹیسٹ کریں۔",
  grade: (n: number) => `جماعت ${n}`,
  roll: (r: string) => `رول نمبر ${r}`,
  role: { new: "نیا", returning: "دوبارہ" },
  status: { listed: "ٹیسٹ باقی", tested: "ٹیسٹ ہو گیا", absent: "غیر حاضر", refused: "انکار", absent_final: "غیر حاضر", pending: "ٹیسٹ باقی" },
  alternates: "اگر کوئی بچہ غیر حاضر ہو تو رومی اگلا بچہ شامل کرے گا:",
  noClassList: "اس سکول کی جماعت 3 یا 5 کی فہرست ابھی موجود نہیں۔",
  frameExhausted: "اس جماعت کے سب بچوں کا اس سہ ماہی ٹیسٹ ہو چکا ہے۔",
  isHere: "کیا یہ بچہ موجود ہے؟",
  present: "حاضر — شروع کریں",
  absent: "غیر حاضر",
  refused: "ٹیسٹ سے انکار",
  continue: "جاری رکھیں",
  blocks: { urdu: "اردو", english: "انگریزی", maths: "ریاضی" },
  step: (i: number, n: number) => `حصہ ${i} از ${n}`,
  turnPhone: "فون بچے کی طرف کریں۔",
  sayCue: (cue: string) => `«${cue}» کہیں، پھر شروع دبائیں۔`,
  sayCueMaths: "پہلے شروع دبائیں، پھر بچے سے اعداد پڑھوائیں۔",
  start: "شروع",
  stop: "روکیں",
  childFinished: "پڑھائی مکمل",
  childFinishedMaths: "سوال مکمل",
  cantRead: "پہلی سطر نہیں پڑھی گئی",
  timeUp: "وقت ختم",
  secondsLeft: "سیکنڈ",
  recordingOn: "ریکارڈنگ جاری",
  afterStory: "اب سوال پوچھیں۔ پھر پہلی آوازیں اور بے معنی الفاظ۔",
  ask: "پوچھیں",
  firstSoundOf: "پہلی آواز",
  madeUpWords: "بے معنی الفاظ (بچہ پڑھے)",
  fallbackTitle: "پہلے حروف، پھر الفاظ",
  numbersTitle: "اعداد",
  startSums: "جلدی والے سوال شروع",
  sumsTitle: "جلدی والے سوال",
  stripNow: "بچے کو کاغذ کی پٹی دیں، پھر روکیں دبائیں۔",
  stopRule: "لگاتار 4 غلط ہوں تو روک دیں۔",
  recorded: (t: string) => `ریکارڈنگ ${t}`,
  listen: "سنیں",
  recordAgain: "دوبارہ ریکارڈ",
  send: "بھیجیں",
  next: "اگلا",
  photoTitle: "ریاضی کی پٹی کی تصویر",
  photoSub: "جب بچہ لکھ چکے۔ پوری پٹی تصویر میں ہو۔",
  takePhoto: "تصویر لیں",
  retakePhoto: "دوبارہ لیں",
  noPhoto: "پٹی کی تصویر نہیں",
  sending: "بھیجا جا رہا ہے…",
  sent: "بھیج دیا",
  savedOnPhone: "اس فون پر محفوظ ہے۔ انٹرنیٹ آنے پر چلا جائے گا۔",
  notSent: "نہیں بھیجا گیا۔",
  refusedBy: (reason: string) => `رومی نے یہ قبول نہیں کیا (${reason})۔`,
  micBlocked: "مائیکروفون استعمال نہیں ہو رہا۔ فون کی سیٹنگز میں اجازت دیں۔",
  micAllow: "جب فون پوچھے تو Allow دبائیں۔",
  unsent: (n: number) => `${n} بھیجنا باقی`,
  sendNow: "ابھی بھیجیں",
  checkTitle: "رومی نے کیا سنا",
  check: "جانچیں",
  marking: "نمبر تیار ہو رہے ہیں…",
  markFailed: "رومی یہ حصہ نہیں جانچ پایا۔ براہ کرم خود نمبر لگائیں۔",
  waitingMedia: "ریکارڈنگ کا انتظار ہے۔",
  wordsCorrect: "60 سیکنڈ میں درست پڑھے گئے الفاظ",
  heardWrong: "رومی کے مطابق یہ الفاظ غلط پڑھے گئے۔ جو لفظ درست پڑھا گیا اس کا نشان ہٹائیں۔",
  notSure: "رومی کو ان پر یقین نہیں۔ جو لفظ غلط پڑھا گیا اس پر نشان لگائیں۔",
  correct: "درست",
  wrong: "غلط",
  noAnswer: "جواب نہیں",
  rumiThinks: (x: string) => `رومی کا اندازہ: ${x}`,
  rumiUnsure: "رومی کو یقین نہیں — براہِ کرم دیکھ لیں",
  rumiUnsureBanner: "رومی نے جو خانے جانچے، وہاں نمبر بھر دیے گئے ہیں۔ جن پر «رومی کو یقین نہیں» لکھا ہے، انہیں ضرور دیکھ لیں۔",
  questions: "سوال",
  firstSounds: "پہلی آوازیں",
  nonwords: "بے معنی الفاظ",
  fallbackLetters: "درست حروف (10 میں سے)",
  fallbackWords: "درست الفاظ (10 میں سے)",
  numbers: "اعداد",
  quickSumsCorrect: "درست جلدی والے سوال",
  written: "لکھے ہوئے سوال (تصویر سے)",
  answerRead: (a: string) => `پڑھا گیا جواب: ${a}`,
  wordProblem: "عبارتی سوال",
  saveCheck: "محفوظ کریں",
  saved: "محفوظ",
  fillAll: "براہ کرم ہر خانہ پُر کریں۔",
  saveFailed: "محفوظ نہیں ہوا۔ دوبارہ کوشش کریں۔",
  childDone: "فہرست پر واپس",
  checkLater: "بعد میں جانچیں",
  allChecked: "سب جانچ لیا",
};

export const COPY: Record<Lang, Copy> = { en, ur };
export type ChildTestCopy = Copy;
