/**
 * quiz-multi-select-flow.json — structural test for the STATIC WhatsApp Flow
 * asset that serves "select all that apply" transcript-quiz questions.
 *
 * Static (no data_api_version, no endpoint_uri): everything the child reads is
 * supplied per-send as navigate-mode screen data, because one Flow asset is
 * shared by the whole WABA and cannot be re-rendered per language (see
 * .claude/skills/whatsapp-flows/SKILL.md rule 12).
 */

const fs = require('fs');
const path = require('path');

const FLOW_JSON_PATH = path.resolve(
  __dirname,
  '../../docs/flows/quiz-multi-select-flow.json',
);

function loadFlow() {
  const raw = fs.readFileSync(FLOW_JSON_PATH, 'utf8');
  return JSON.parse(raw);
}

// Recursively collect every layout node so ${data.X} references anywhere in
// the tree (not just direct children) are found.
function collectNodes(node, acc = []) {
  if (Array.isArray(node)) {
    for (const n of node) collectNodes(n, acc);
    return acc;
  }
  if (node && typeof node === 'object') {
    acc.push(node);
    for (const v of Object.values(node)) collectNodes(v, acc);
  }
  return acc;
}

function findDataBindings(layout) {
  const bindings = new Set();
  const seen = new Set();
  const walk = (val) => {
    if (typeof val === 'string') {
      const re = /\$\{data\.([a-zA-Z_][a-zA-Z0-9_]*)\}/g;
      let m;
      while ((m = re.exec(val)) !== null) bindings.add(m[1]);
      return;
    }
    if (Array.isArray(val)) {
      for (const v of val) walk(v);
      return;
    }
    if (val && typeof val === 'object') {
      for (const v of Object.values(val)) walk(v);
    }
  };
  walk(layout);
  return bindings;
}

function findFooter(layout) {
  const nodes = collectNodes(layout);
  return nodes.find((n) => n.type === 'Footer');
}

function findByType(layout, type) {
  const nodes = collectNodes(layout);
  return nodes.find((n) => n.type === type);
}

describe('quiz-multi-select-flow.json', () => {
  test('the file exists and parses as JSON', () => {
    expect(fs.existsSync(FLOW_JSON_PATH)).toBe(true);
    expect(() => loadFlow()).not.toThrow();
  });

  test('exactly one screen, id PICK, terminal: true', () => {
    const flow = loadFlow();
    expect(flow.screens).toHaveLength(1);
    expect(flow.screens[0].id).toBe('PICK');
    expect(flow.screens[0].terminal).toBe(true);
  });

  test('declares no data_api_version and no endpoint_uri (a static Flow)', () => {
    const flow = loadFlow();
    expect(flow.data_api_version).toBeUndefined();
    expect(flow.endpoint_uri).toBeUndefined();
    // Guard the whole tree, not just top-level, in case an endpoint URI is
    // nested (e.g. inside a screen action) instead.
    expect(JSON.stringify(flow)).not.toMatch(/endpoint_uri/);
  });

  test('every ${data.X} reference in the layout is declared in data', () => {
    const flow = loadFlow();
    const screen = flow.screens[0];
    const declared = new Set(Object.keys(screen.data || {}));
    const referenced = findDataBindings(screen.layout);
    const undeclared = [...referenced].filter((k) => !declared.has(k));
    expect(undeclared).toEqual([]);
  });

  test("the Footer's on-click-action.name is complete", () => {
    const flow = loadFlow();
    const footer = findFooter(flow.screens[0].layout);
    expect(footer).toBeDefined();
    expect(footer['on-click-action'].name).toBe('complete');
  });

  test('the completion payload carries picks, answer_token and quiz_multi_action', () => {
    const flow = loadFlow();
    const footer = findFooter(flow.screens[0].layout);
    const payload = footer['on-click-action'].payload;
    expect(Object.keys(payload).sort()).toEqual(
      ['answer_token', 'picks', 'quiz_multi_action'].sort(),
    );
  });

  test('quiz_multi_action is the literal string "answer", not a data binding', () => {
    const flow = loadFlow();
    const footer = findFooter(flow.screens[0].layout);
    expect(footer['on-click-action'].payload.quiz_multi_action).toBe('answer');
  });

  /**
   * Verified in the live Flow preview on 2026-09-06: Meta renders its OWN helper
   * line under the label from these two properties — "Choose 1 to 4 options." —
   * in English, generated by the client and not supplied by us. On an Urdu quiz
   * that is an untranslatable English sentence under an Urdu instruction.
   *
   * Neither property bought anything. `required: true` already blocks an empty
   * submit (the Send button stays disabled with nothing ticked, seen in the same
   * preview), and a maximum equal to the option count is not a constraint. A
   * maximum equal to the number of CORRECT options would have been actively
   * harmful — it hands the child the size of the answer key.
   */
  test('no min/max-selected-items: they add an untranslatable English helper line', () => {
    const flow = loadFlow();
    const checkbox = findByType(flow.screens[0].layout, 'CheckboxGroup');
    expect(checkbox).toBeDefined();
    expect(checkbox).not.toHaveProperty('max-selected-items');
    expect(checkbox).not.toHaveProperty('min-selected-items');
    expect(checkbox.required).toBe(true);
  });

  test('nothing in the Flow reveals how many options are correct', () => {
    const flow = loadFlow();
    const asText = JSON.stringify(flow.screens[0]);
    expect(asText).not.toMatch(/correct/i);
    expect(Object.keys(flow.screens[0].data)).not.toContain('max_selected');
  });

  test('there is no sibling RadioButtonsGroup (multi-answer only)', () => {
    const flow = loadFlow();
    expect(findByType(flow.screens[0].layout, 'RadioButtonsGroup')).toBeUndefined();
  });

  test("the CheckboxGroup's label is data-bound, not a hardcoded English string", () => {
    const flow = loadFlow();
    const checkbox = findByType(flow.screens[0].layout, 'CheckboxGroup');
    expect(checkbox.label).toMatch(/^\$\{data\.[a-zA-Z_][a-zA-Z0-9_]*\}$/);
  });

  test('screens[0].title is <= 30 code points', () => {
    const flow = loadFlow();
    const title = flow.screens[0].title;
    expect(typeof title).toBe('string');
    expect([...title].length).toBeLessThanOrEqual(30);
  });
});
