/**
 * bd-fmf24g.7 — every word the teacher v2 Attendance screens show, in the feature's own copy file.
 * Same rules as the new UI's copy: 1–3 words, 4 at most, no sentences. English only for now; the Urdu
 * pass gives each key an Urdu value. DATA is not copy: a class's name, a child's name and the subject
 * names come from the API as they are.
 */
export const ATTENDANCE_V2_COPY = {
  title: 'Attendance',
  home: 'Home',
  /* the selector */
  view: 'View',
  download: 'Download',
  search: 'Search class or subject',
  clear: 'Clear',
  notMarked: 'Not marked',
  marked: 'Marked',
  markedOf: (present: number, total: number) => `Marked ${present}/${total}`,
  students: (n: number) => `${n} students`,
  noClass: 'No class found',
  noClasses: 'No classes yet',
  /* the roll call */
  markTitle: 'Mark attendance',
  today: 'Today',
  yesterday: 'Yesterday',
  pickDate: 'Pick date',
  date: 'Date',
  alreadyMarked: 'Already marked',
  allPresent: 'All present',
  searchStudent: 'Search student',
  noStudent: 'No student found',
  noStudents: 'No students yet',
  present: 'Present',
  absent: 'Absent',
  leave: 'Leave',
  presentShort: 'P',
  absentShort: 'A',
  leaveShort: 'L',
  save: 'Save',
  saveChanges: 'Save changes',
  saving: 'Saving',
  saveFailed: 'Not saved',
  saved: 'Saved',
  presentCount: (n: number) => `${n} present`,
  absentCount: (n: number) => `${n} absent`,
  leaveCount: (n: number) => `${n} leave`,
  monthRegister: 'Month register',
  excel: 'Excel',
  viewAttendance: 'View attendance',
  edit: 'Edit',
  nextClass: 'Next class',
  /* the view */
  viewTitle: 'Class attendance',
  change: 'Change',
  chooseClass: 'Choose class',
  prevMonth: 'Previous month',
  nextMonth: 'Next month',
  hi: '90%+',
  mid: '75–89%',
  lo: 'Below 75%',
  unmarked: 'Not marked',
  ofTotal: (present: number, total: number) => `${present} of ${total}`,
  markNow: 'Mark now',
  everyonePresent: 'Everyone present',
  studentsTitle: 'Students',
  lowestFirst: 'Lowest first',
  allStudents: (n: number) => `All ${n} students`,
  fewer: 'Show fewer',
  pct: (n: number) => `${n}%`,
  daysOf: (present: number, marked: number) => `${present} of ${marked} days`,
  noValue: '—',
  nothingThisMonth: 'Nothing marked yet',
  /* download */
  downloadTitle: 'Download register',
  month: 'Month',
  thisMonth: 'This month',
  lastMonth: 'Last month',
  otherMonth: 'Other month',
  register: 'Register',
  daysMarked: (n: number) => `${n} days marked`,
  whatsapp: 'WhatsApp',
  sent: 'Sent',
  notSent: 'Not sent',
  downloadFailed: 'Not downloaded',
  /* shared */
  failed: 'Could not load',
  retry: 'Try again',
  loading: 'Loading',
};

export type AttendanceCopy = typeof ATTENDANCE_V2_COPY;
